name: Update_MaxMind.yml

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download MaxMind
        env:
          LICENSE_KEY: ${{ secrets.LICENSE_KEY }}
        run: |
          mkdir -p Maxmind

          curl -L "https://download.maxmind.com/app/geoip_download?edition_id=GeoLite2-ASN&license_key=${LICENSE_KEY}&suffix=tar.gz" -o Maxmind/GeoLite2-ASN.tar.gz
          curl -L "https://download.maxmind.com/app/geoip_download?edition_id=GeoLite2-ASN-CSV&license_key=${LICENSE_KEY}&suffix=zip" -o Maxmind/GeoLite2-ASN-CSV.zip
          curl -L "https://download.maxmind.com/app/geoip_download?edition_id=GeoLite2-Country&license_key=${LICENSE_KEY}&suffix=tar.gz" -o Maxmind/GeoLite2-Country.tar.gz
          curl -L "https://download.maxmind.com/app/geoip_download?edition_id=GeoLite2-Country-CSV&license_key=${LICENSE_KEY}&suffix=zip" -o Maxmind/GeoLite2-Country-CSV.zip

      - name: Commit files
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"

          git add Maxmind/*
          git commit -m "update maxmind database" || echo "no change"
          git push
