name: Update MaxMind

on:
  schedule:
    - cron: "30 21 * * *"
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
        with:
          token: ${{ secrets.PAT }}

      - env:
          LICENSE_KEY: ${{ secrets.MAXMIND_GEOLITE2_LICENSE }}
        run: |
          mkdir -p ./Maxmind
          curl -L "https://download.maxmind.com/app/geoip_download?edition_id=GeoLite2-ASN&license_key=${LICENSE_KEY}&suffix=tar.gz" -o ./Maxmind/GeoLite2-ASN.tar.gz
          curl -L "https://download.maxmind.com/app/geoip_download?edition_id=GeoLite2-ASN-CSV&license_key=${LICENSE_KEY}&suffix=zip" -o ./Maxmind/GeoLite2-ASN-CSV.zip
          curl -L "https://download.maxmind.com/app/geoip_download?edition_id=GeoLite2-Country&license_key=${LICENSE_KEY}&suffix=tar.gz" -o ./Maxmind/GeoLite2-Country.tar.gz
          curl -L "https://download.maxmind.com/app/geoip_download?edition_id=GeoLite2-Country-CSV&license_key=${LICENSE_KEY}&suffix=zip" -o ./Maxmind/GeoLite2-Country-CSV.zip

      - run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add Maxmind/*
          git commit -m "update maxmind database" || exit 0
          git push